language: c
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
     - check
     - libopenmpi-dev
     - openmpi-bin
     - libpq-dev
script:
 - autoreconf -ivf
 - mkdir -v build
 - cd build
 - ../configure --prefix=${HOME}
 - make check
