language: c
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
     - check
     - libopenmpi-dev
     - openmpi-bin
     - postgresql-9.2
script:
 - mkdir -v build
 - cd build
 - autoreconf -ivf ..
 - ../configure --prefix=${HOME}
 - make check
